<a href="https://colab.research.google.com/github/EnriqueRangel/Telecom_X/blob/main/Challenge_Telecom_X.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 📌 Extracción

In [1]:
import requests
import pandas as pd

url = 'https://raw.githubusercontent.com/ingridcristh/challenge2-data-science-LATAM/refs/heads/main/TelecomX_Data.json'
response = requests.get(url)
data = response.json()

df = pd.DataFrame(data)
print(df.head())

   customerID Churn                                           customer  \
0  0002-ORFBO    No  {'gender': 'Female', 'SeniorCitizen': 0, 'Part...
1  0003-MKNFE    No  {'gender': 'Male', 'SeniorCitizen': 0, 'Partne...
2  0004-TLHLJ   Yes  {'gender': 'Male', 'SeniorCitizen': 0, 'Partne...
3  0011-IGKFF   Yes  {'gender': 'Male', 'SeniorCitizen': 1, 'Partne...
4  0013-EXCHZ   Yes  {'gender': 'Female', 'SeniorCitizen': 1, 'Part...

                                             phone  \
0   {'PhoneService': 'Yes', 'MultipleLines': 'No'}
1  {'PhoneService': 'Yes', 'MultipleLines': 'Yes'}
2   {'PhoneService': 'Yes', 'MultipleLines': 'No'}
3   {'PhoneService': 'Yes', 'MultipleLines': 'No'}
4   {'PhoneService': 'Yes', 'MultipleLines': 'No'}

                                            internet  \
0  {'InternetService': 'DSL', 'OnlineSecurity': '...
1  {'InternetService': 'DSL', 'OnlineSecurity': '...
2  {'InternetService': 'Fiber optic', 'OnlineSecu...
3  {'InternetService': 'Fiber optic', 'OnlineSecu...
4  {'InternetService': 'Fiber optic', 'OnlineSecu...

                                             account
0  {'Contract': 'One year', 'PaperlessBilling': '...
1  {'Contract': 'Month-to-month', 'PaperlessBilli...
2  {'Contract': 'Month-to-month', 'PaperlessBilli...
3  {'Contract': 'Month-to-month', 'PaperlessBilli...
4  {'Contract': 'Month-to-month', 'PaperlessBilli...

### Diccionario de datos

* customerID: número de identificación único de cada cliente
* Churn: si el cliente dejó o no la empresa
* gender: género (masculino y femenino)
* SeniorCitizen: información sobre si un cliente tiene o no una edad igual o mayor a 65 años
* Partner: si el cliente tiene o no una pareja
* Dependents: si el cliente tiene o no dependientes
* tenure: meses de contrato del cliente
* PhoneService: suscripción al servicio telefónico
* MultipleLines: suscripción a más de una línea telefónica
* InternetService: suscripción a un proveedor de internet
* OnlineSecurity: suscripción adicional de seguridad en línea
* OnlineBackup: suscripción adicional de respaldo en línea
* DeviceProtection: suscripción adicional de protección del dispositivo
* TechSupport: suscripción adicional de soporte técnico, menor tiempo de espera
* StreamingTV: suscripción de televisión por cable
* StreamingMovies: suscripción de streaming de películas
* Contract: tipo de contrato
* PaperlessBilling: si el cliente prefiere recibir la factura en línea
* PaymentMethod: forma de pago
* Charges.Monthly: total de todos los servicios del cliente por mes
* Charges.Total: total gastado por el cliente

In [2]:
from pandas import json_normalize
df_normalize = json_normalize(data)
df_normalize.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customerID                 7267 non-null   object
 1   Churn                      7267 non-null   object
 2   customer.gender            7267 non-null   object
 3   customer.SeniorCitizen     7267 non-null   int64
 4   customer.Partner           7267 non-null   object
 5   customer.Dependents        7267 non-null   object
 6   customer.tenure            7267 non-null   int64
 7   phone.PhoneService         7267 non-null   object
 8   phone.MultipleLines        7267 non-null   object
 9   internet.InternetService   7267 non-null   object
 10  internet.OnlineSecurity    7267 non-null   object
 11  internet.OnlineBackup      7267 non-null   object
 12  internet.DeviceProtection  7267 non-null   object
 13  internet.TechSupport       7267 non-null   object
 14  internet.StreamingTV       7267 non-null   object
 15  internet.StreamingMovies   7267 non-null   object
 16  account.Contract           7267 non-null   object
 17  account.PaperlessBilling   7267 non-null   object
 18  account.PaymentMethod      7267 non-null   object
 19  account.Charges.Monthly    7267 non-null   float64
 20  account.Charges.Total      7267 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.2+ MB

In [14]:
df_normalize.describe(include='all')

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,...,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total
count,7267,7267,7267,7267.000000,7267,7267,7267.000000,7267,7267,7267,...,7267,7267,7267,7267,7267,7267,7267,7267,7267.000000,7267
unique,7267,3,2,NaN,2,2,NaN,2,3,3,...,3,3,3,3,3,3,2,4,NaN,6531
top,9995-HOTOH,No,Male,NaN,No,No,NaN,Yes,No,Fiber optic,...,No,No,No,No,No,Month-to-month,Yes,Electronic check,NaN,20.2
freq,1,5174,3675,NaN,3749,5086,NaN,6560,3495,3198,...,3182,3195,3582,2896,2870,4005,4311,2445,NaN,11
mean,NaN,NaN,NaN,0.162653,NaN,NaN,32.346498,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64.720098,NaN
std,NaN,NaN,NaN,0.369074,NaN,NaN,24.571773,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.129572,NaN
min,NaN,NaN,NaN,0.000000,NaN,NaN,0.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.250000,NaN
25%,NaN,NaN,NaN,0.000000,NaN,NaN,9.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.425000,NaN
50%,NaN,NaN,NaN,0.000000,NaN,NaN,29.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70.300000,NaN
75%,NaN,NaN,NaN,0.000000,NaN,NaN,55.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89.875000,NaN
max,NaN,NaN,NaN,1.000000,NaN,NaN,72.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,118.750000,NaN

In [15]:
df_normalize.isnull().sum()

customerID                   0
Churn                        0
customer.gender              0
customer.SeniorCitizen       0
customer.Partner             0
customer.Dependents          0
customer.tenure              0
phone.PhoneService           0
phone.MultipleLines          0
internet.InternetService     0
internet.OnlineSecurity      0
internet.OnlineBackup        0
internet.DeviceProtection    0
internet.TechSupport         0
internet.StreamingTV         0
internet.StreamingMovies     0
account.Contract             0
account.PaperlessBilling     0
account.PaymentMethod        0
account.Charges.Monthly      0
account.Charges.Total        0
dtype: int64

In [19]:
df_normalize.head(30)

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,...,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.60,593.3
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.90,542.4
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.90,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.00,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.90,267.4
5,0013-MHZWF,No,Female,0,No,Yes,9,Yes,No,DSL,...,No,No,Yes,Yes,Yes,Month-to-month,Yes,Credit card (automatic),69.40,571.45
6,0013-SMEOE,No,Female,1,Yes,No,71,Yes,No,Fiber optic,...,Yes,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),109.70,7904.25
7,0014-BMAQU,No,Male,0,Yes,No,63,Yes,Yes,Fiber optic,...,No,No,Yes,No,No,Two year,Yes,Credit card (automatic),84.65,5377.8
8,0015-UOCOJ,No,Female,1,No,No,7,Yes,No,DSL,...,No,No,No,No,No,Month-to-month,Yes,Electronic check,48.20,340.35
9,0016-QLJIS,No,Female,0,Yes,Yes,65,Yes,Yes,DSL,...,Yes,Yes,Yes,Yes,Yes,Two year,Yes,Mailed check,90.45,5957.9
10,0017-DINOC,No,Male,0,No,No,54,No,No phone service,DSL,...,No,No,Yes,Yes,No,Two year,No,Credit card (automatic),45.20,2460.55
11,0017-IUDMW,No,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,...,Yes,Yes,Yes,Yes,Yes,Two year,Yes,Credit card (automatic),116.80,8456.75
12,0018-NYROU,No,Female,0,Yes,No,5,Yes,No,Fiber optic,...,No,No,No,No,No,Month-to-month,Yes,Electronic check,68.95,351.5
13,0019-EFAEP,No,Female,0,No,No,72,Yes,Yes,Fiber optic,...,Yes,Yes,No,Yes,No,Two year,Yes,Bank transfer (automatic),101.30,7261.25
14,0019-GFNTW,No,Female,0,No,No,56,No,No phone service,DSL,...,Yes,Yes,Yes,No,No,Two year,No,Bank transfer (automatic),45.05,2560.1
15,0020-INWCK,No,Female,0,Yes,Yes,71,Yes,Yes,Fiber optic,...,Yes,Yes,No,No,Yes,Two year,Yes,Credit card (automatic),95.75,6849.4
16,0020-JDNXP,No,Female,0,Yes,Yes,34,No,No phone service,DSL,...,No,Yes,Yes,Yes,Yes,One year,No,Mailed check,61.25,1993.2
17,0021-IKXGC,No,Female,1,No,No,1,Yes,Yes,Fiber optic,...,No,No,No,No,No,Month-to-month,Yes,Electronic check,72.10,72.1
18,0022-TCJCI,Yes,Male,1,No,No,45,Yes,No,DSL,...,No,Yes,No,No,Yes,One year,No,Credit card (automatic),62.70,2791.5
19,0023-HGHWL,Yes,Male,1,No,No,1,No,No phone service,DSL,...,No,No,No,No,No,Month-to-month,Yes,Electronic check,25.10,25.1
20,0023-UYUPN,No,Female,1,Yes,No,50,Yes,Yes,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,One year,No,Electronic check,25.20,1306.3
21,0023-XUOPT,Yes,Female,0,Yes,No,13,Yes,Yes,Fiber optic,...,Yes,Yes,No,Yes,No,Month-to-month,No,Electronic check,94.10,1215.6
22,0027-KWYKW,No,Female,0,Yes,Yes,23,Yes,Yes,Fiber optic,...,No,No,No,Yes,No,Month-to-month,Yes,Electronic check,83.75,1849.95
23,0030-FNXPP,No,Female,0,No,No,3,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Mailed check,19.85,57.2
24,0031-PVLZI,Yes,Female,0,Yes,Yes,4,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Mailed check,20.35,76.35
25,0032-PGELS,Yes,Female,0,Yes,Yes,1,No,No phone service,DSL,...,No,No,No,No,No,Month-to-month,No,Bank transfer (automatic),30.50,30.5
26,0036-IHMOT,No,Female,0,Yes,Yes,55,Yes,No,Fiber optic,...,Yes,Yes,Yes,Yes,Yes,One year,Yes,Bank transfer (automatic),103.70,5656.75
27,0040-HALCW,No,Male,0,Yes,Yes,54,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Credit card (automatic),20.40,1090.6
28,0042-JVWOJ,No,Male,0,No,No,26,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,One year,Yes,Bank transfer (automatic),19.60,471.85
29,0042-RLHYP,No,Female,0,Yes,Yes,69,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Bank transfer (automatic),19.70,1396.9

# **🔧 Transformación**

### Acciones más comunes
* Duplicados
* Valores vacíos
* Valores nulos
* Tipos de datos
* Valores atípicos
* Consistencia y validez de datos categóricos
* Normalización de textos

In [4]:
# Verifique si hay valores únicos en cada columna
for col in df_normalize. columns:
 print(f"valores únicos en la columna'{col}': {df_normalize[col] .nunique()}")
 if df_normalize[col].nunique() < 50: # Imprima los valores solamente si no hay muchos
   print(df_normalize[col] .unique())
   print('-' * 50)
# Línea divisoria para mejor visualización

valores únicos en la columna'customerID': 7267
valores únicos en la columna'Churn': 3
['No' 'Yes' '']
--------------------------------------------------
valores únicos en la columna'customer.gender': 2
['Female' 'Male']
--------------------------------------------------
valores únicos en la columna'customer.SeniorCitizen': 2
[0 1]
--------------------------------------------------
valores únicos en la columna'customer.Partner': 2
['Yes' 'No']
--------------------------------------------------
valores únicos en la columna'customer.Dependents': 2
['Yes' 'No']
--------------------------------------------------
valores únicos en la columna'customer.tenure': 73
valores únicos en la columna'phone.PhoneService': 2
['Yes' 'No']
--------------------------------------------------
valores únicos en la columna'phone.MultipleLines': 3
['No' 'Yes' 'No phone service']
--------------------------------------------------
valores únicos en la columna'internet.InternetService': 3
['DSL' 'Fiber optic' 'No']
--------------------------------------------------
valores únicos en la columna'internet.OnlineSecurity': 3
['No' 'Yes' 'No internet service']
--------------------------------------------------
valores únicos en la columna'internet.OnlineBackup': 3
['Yes' 'No' 'No internet service']
--------------------------------------------------
valores únicos en la columna'internet.DeviceProtection': 3
['No' 'Yes' 'No internet service']
--------------------------------------------------
valores únicos en la columna'internet.TechSupport': 3
['Yes' 'No' 'No internet service']
--------------------------------------------------
valores únicos en la columna'internet.StreamingTV': 3
['Yes' 'No' 'No internet service']
--------------------------------------------------
valores únicos en la columna'internet.StreamingMovies': 3
['No' 'Yes' 'No internet service']
--------------------------------------------------
valores únicos en la columna'account.Contract': 3
['One year' 'Month-to-month' 'Two year']
--------------------------------------------------
valores únicos en la columna'account.PaperlessBilling': 2
['Yes' 'No']
--------------------------------------------------
valores únicos en la columna'account.PaymentMethod': 4
['Mailed check' 'Electronic check' 'Credit card (automatic)'
 'Bank transfer (automatic)']
--------------------------------------------------
valores únicos en la columna'account.Charges.Monthly': 1585
valores únicos en la columna'account.Charges.Total': 6531

In [5]:
# Verificando si hay duplicados
duplicados = df_normalize.duplicated().sum()
print(f"Numero de lineas duplicadas: {duplicados}")
# Verificando si hay valores Nulos
valores_nulos = df_normalize.isnull().values.sum()
print("\nValores nulos por columna:")
print(valores_nulos [valores_nulos > 0])

Numero de lineas duplicadas: 0

Valores nulos por columna:
[]

In [6]:
  valores_en_blancos_o_vacio = df_normalize.apply(lambda x: x.astype(str).str.strip() == '').sum()
  print("\nValores en blanco o string vacios por columna:")
  print(valores_en_blancos_o_vacio[valores_en_blancos_o_vacio > 0])

Valores en blanco o string vacios por columna:
Churn                    224
account.Charges.Total     11
dtype: int64

# 📊 Carga y análisis

# 📄Informe final